### ISSUE TITLE
Default configuration throwing error 'Task never defined'

### ISSUE THREAD

**Issue by Mcdonamj087** [cferdinandi/gulp-boilerplate#76] opened 2019-04-26 03:52 UTC
Upon default configuration and following initial instructions, i'm trying to run the 'gulp' and 'gulp-watch' tasks, but am met with 'Task never defined' errors.  Can't seem to figure out why.  I'm running the latest Gulp and Gulp CLI.  

See attached screenshot:

<img width="521" alt="Screen Shot 2019-04-25 at 10 33 22 PM" src="https://user-images.githubusercontent.com/17895186/56782425-af06b900-67ac-11e9-9227-738133eddd37.png">

**Comment by miclgael** [comment] 2019-04-26 06:42
Hi @iandanforth - I had the same thing and in my case I think it might have been caused by not having a repository + url set in my `package.json`. I think I have a fix for that, but wonder if you would mind checking for those in your pkg?

**Comment by Mcdonamj087** [comment] 2019-04-26 13:13
My repository and url are the defaults that were included in Chris’s boilerplate.  Repo address and website url shouldn't affect gulp in the way that it’s tossing these errors as if the tasks aren't written.  It’s even explicitly telling me that it’s looking in the gulpfile located inside my project root, so i’m at a loss.

**Comment by cferdinandi** [comment] 2019-04-26 13:38
I'm going to do a fresh install right now and test this.

**Comment by cferdinandi** [comment] 2019-04-26 13:46
This is bizarre. I cannot replicate, and, I mean, the task is clearly defined in `gulpfile.js`. That error makes no sense. Sigh.

**Comment by Mcdonamj087** [comment] 2019-04-26 13:58
@cferdinandi so everything working on your end i assume?  What versions of Gulp CLI are you running?  I gotta think this is probably some sort of discrepancy in my versioning.  I’m going to try this on another computer and see if i can replicate again.  Will report back soon!

**Comment by Mcdonamj087** [comment] 2019-04-26 14:46
@cferdinandi I was able to find a fix!  I needed to update gulp to 4.0.1 (the latest).  I grabbed a fresh download from your repo, changed the gulp version from 4.0.0 to 4.0.1 in your package.json and ran npm install as normal.  Everything is working now!

**Comment by cferdinandi** [comment] 2019-04-26 14:51
How very bizarre. I'll update the files on my end, too. Cheers!

**Comment by miclgael** [comment] 2019-04-27 05:15
I just realised I had already updated to 4.0.1 so this makes sense for me too!

**Comment by james0r** [comment] 2019-04-28 17:38
Upgrading to Gulp 4.0.1 did it for me too.

**Comment by atazminhlk** [comment] 2019-05-24 02:34
Upgrading to Gulp 4.0.1 did it for me too.

**Comment by dssorokin** [comment] 2019-06-04 20:49
@Mcdonamj087 You saved my time. Thanks a lot!

**Comment by mario-cvetkovski** [comment] 2019-07-16 21:58
I had the same error like this. I fixed the error with "npm install gulp --save-dev", after the "npm install" command.

**Comment by cferdinandi** [comment] 2019-08-14 18:57
This should be fixed with the latest build. Sorry it's taken me so damn long!

**Closed by cferdinandi** 2019-08-14 18:57 UTC
Labels: bug, help wanted

**Comment by subhadande** [comment] 2019-11-29 08:38
This is my gulpfile.js,

var gulp = require("gulp");
var ts = require("gulp-typescript");
var tsProject = ts.createProject("tsconfig.json");
gulp.task("default", function() {
return tsProject.src().pipe(tsProject()).js.pipe(gulp.dest("dist"))
});

This is the version of gulp,
CLI version: 2.2.0
Local version: 4.0.2

But while running the command "gulp; node dist/app.js" I am getting this error 'Task never defined'

Can you please help me on this
