### ISSUE TITLE
Live Reload doesn't seem to be working properly

### ISSUE THREAD

**Issue by davidkabo** [cferdinandi/gulp-boilerplate#51] opened 2016-08-12 11:59 UTC
In my windows cmd i get the following message when running gulp:

'undefined reloaded'. Do you have any ideas how to fix this? Anyone experienced the same error?

Thanks in advance

**Comment by cferdinandi** [comment] 2016-08-12 13:47
Hi @davidkabo - Did you get this figured out? If so, mind sharing what you did in case anyone else runs into this issue?

**Comment by davidkabo** [comment] 2016-08-12 20:42
Hi @cferdinandi, unfortunately I didn't manage to fix the problem. I am new to Gulp and JS...

https://github.com/vohof/gulp-livereload/issues/102

CNSam had the same prb, however I cannot make anything out of the replies.

**Comment by cferdinandi** [comment] 2016-08-13 18:41
That actually helps a lot! The problem is [with this line](https://github.com/cferdinandi/gulp-boilerplate/blob/master/gulpfile.js#L273):

```js
livereload.changed();
```

An argument is supposed to be passed into `changed()` like so:

```js
livereload.changed(path);
```

This is a change that was introduced in v3 that I completely missed. Still trying to figure out exactly what `path` should be, but I'll update once I get this sorted out.

**Comment by davidkabo** [comment] 2016-08-13 19:40
Ok cool. Anyway all in all your boilerplate is awesome. Thanks for putting it on GH and thanks as well to the ppl helping to improve it.

**Comment by cferdinandi** [comment] 2016-08-15 13:59
This should be fixed now with https://github.com/cferdinandi/gulp-boilerplate/pull/52

**Closed by cferdinandi** 2016-08-15 13:59 UTC
